### ISSUE TITLE
Running hello world example from docs yields import error on evwsgi

### ISSUE THREAD

**Issue by eric-tucker** [william-os4y/fapws3#41]
http://www.fapws.org/getting-started

````
[etucker: ]$ ./fapws.py
Traceback (most recent call last):
  File "fapws.py", line 2, in <module>
    import fapws.evwsgi as evwsgi
  File "fapws.py", line 2, in <module>
    import fapws.evwsgi as evwsgi
ImportError: No module named evwsgi
````

I've tried install fapws3 from both PIP and compiling from source.  It does not work.

This is on both Fedora and Amazon EC2 using Python 2.7.

**Comment by eric-tucker** [comment]
Update - compiling from source works.  I must not have closed my terminal or something.  So the PIP version needs to be updated.

**Comment by william-os4y** [comment]
Nice to see it works. 
Such troubles are strongly linked to your system and the way packages (and libraries) are managed. 


On 8 December 2015 20:44:43 CET, eric-tucker <notifications@github.com> wrote:
>Update - compiling from source works.  I must not have closed my
>terminal or something.  So the PIP version needs to be updated.  
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/william-os4y/fapws3/issues/41#issuecomment-162993713

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by eric-tucker** [comment]
I agree - the way packages are installed via PIP and able to go to multiple locations (lib / lib64, python2.7 / python3.4, site-packages / dist-packages) is very confusing and probably a source of this headache.

That being said, other packages just seem to "work" when installed via PIP.  I don't feel comfortable using a system which does not work unless installed from source.  PIP installs should work, do you not agree?
